FROM restic/restic:0.19.0@sha256:7f44e0057b82348597568ea209360762d0b38f8e1dbc8ad859661ac1055e45f2

USER root
RUN apk add --no-cache bash ca-certificates curl jq mariadb-client sqlite

ENTRYPOINT []
CMD ["/bin/bash"]
