FROM restic/restic:0.19.1@sha256:136600b6ff6843d61d355f7f71f460a166429f35de6fd11b568fece3c9a4d510

USER root
RUN apk add --no-cache bash ca-certificates curl jq mariadb-client sqlite

ENTRYPOINT []
CMD ["/bin/bash"]
