apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  hostPath:
    path: /opt/romm
    type: DirectoryOrCreate
  claimRef:
    namespace: media
    name: romm-data-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-data-pvc
  namespace: media
spec:
  storageClassName: local-nvme
  accessModes:
    - ReadWriteOnce
  volumeName: romm-data-pv
  resources:
    requests:
      storage: 20Gi
