apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  podMetricsEndpoints:
    - port: http-prom
      interval: 30s
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: flux
