apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app.kubernetes.io/name: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
    spec:
      priorityClassName: homelab-standard
      securityContext:
        supplementalGroups:
          - 993
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex:1.43.3.10896-cb3ebc72d-ls322@sha256:7f9a1d574958fc2f177c14ca190d4b811a58c274477f5bae8fb44ee676fb96bf
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
            - name: VERSION
              value: docker
          ports:
            - name: http
              containerPort: 32400
          resources:
            requests:
              cpu: "1"
              memory: 1536Mi
              gpu.intel.com/i915: "1"
            limits:
              cpu: "6"
              memory: 4Gi
              gpu.intel.com/i915: "1"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
              readOnly: true
            - name: media
              mountPath: /mnt/media
              readOnly: true
            - name: transcode
              mountPath: /transcode
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config-pvc
        - name: media
          hostPath:
            path: /mnt/media
            type: Directory
        - name: transcode
          persistentVolumeClaim:
            claimName: plex-transcode-pvc
