apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  hostPath:
    path: /opt/plex/config
    type: DirectoryOrCreate
  claimRef:
    namespace: media
    name: plex-config-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
  namespace: media
spec:
  storageClassName: local-nvme
  accessModes:
    - ReadWriteOnce
  volumeName: plex-config-pv
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-pvc
  namespace: media
spec:
  storageClassName: topolvm-scratch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
