apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:6xEus+iWDYaJA5AyWeiKN/z1SRYWIX4DyVELnhzmmB7CZ57NKWV3gk+ljfwNNOoM/jtMLdUfdtYYIu8VccKrqdeYJN+E1YJJq0mb8XplH6uqbBdrIx8ZBw==,iv:1/iK+dvPwcQC0fA9u5qmPCL+6G6oyUJKiBR0oijpqZw=,tag:ugcgmWCXZGrHNlOmosa6RQ==,type:str]
    admin-user: ENC[AES256_GCM,data:sKi+Dd6nxM4=,iv:dKMP0wf2dZaCaVKQArTcy9CoDIRXkLWvpCBY1O5NoNw=,tag:eTRdkJdB7Zzub/23yB3WXg==,type:str]
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbndNa2lWM2JzS0kvdk81
            UnNhMWFHQkpOcWJOY0doS1AyUlB4QmNOTjBvCnp0VFA5SkVHZTRRTjU2aXZZbXhO
            Z3BONWZ3VGhnTTNlUXBjcWtsclJieFEKLS0tIFhuUXBzc3FJU2xpZUc2WHU2VXBl
            eXJLZGJja2wvcUpYTnhaRXBwYlZtOUEKxnWRR4g34UaAnKpEeFsR71nHmV3SpnX/
            MQ/4v/sDdUhRwbnlmPP0YV75Idvxu+drHY/wc1ppZGz37KLID7rWwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T02:32:28Z"
    mac: ENC[AES256_GCM,data:6Nm+Bb51PyqCpfBr8pD06HngNtY7hxigt3hozXYbakRCXwBqYUJWuHEBsEm7wyxVsuWRLeJgXh5W6gDyd+xoGsKSjLvvJXYiLWJ/bLltNPDfmdbhrSbWPapqUI+nF2Xonvp0aoRqcKa62juAVF9GGb7NDjnrNgkbupgbeI++TPo=,iv:Yiv5k9YJWTR3mQSthujULiSy00me/lWZYdBG5jPU0HE=,tag:4m+dficceWFzYWF87XZe7g==,type:str]
    version: 3.13.1
