apiVersion: v1
data:
    client_id: ENC[AES256_GCM,data:rezuWA0IgPhhEAax2PN84jPYJfQUPkEq,iv:eKnweZCxO5pUELFm9WaaRUllpb0fq4anHs0rNuFLsfM=,tag:T1gh5bb4cUMXEMQwWNR9mQ==,type:str]
    client_secret: ENC[AES256_GCM,data:6g4brd7GdKCu11nMosS9P421jsRjGp7UbFOTCIjsyPx0BSBBrQ/LehJRNsncwA3kwOcvijnzCgLfwLTfZcupF5RRq8ZjBbWHO0bLWITLtDjYCXo7,iv:H2rESF7qE6hWRORZj56Rjgz8ILUPZbKcFoEJdJ3dy10=,tag:Fc95v8sJZdnWyQAeWkm5eQ==,type:str]
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVVdBMGZqUlFwS3MzR1JT
            aFczZmNjelh3OXVyQ1dzNWVRa3FZRHVaTWlrCnJwOU8wOEljaG0xOE5LQlZ3NmpZ
            Wmp4UXVYamtMMFY1ZkR6WHhxcGtFM0EKLS0tIHE2eUdBb2lFTjRubGhialBsNytq
            ODhGVEsyd0tqZUx3RWpKVDBuSUU4emsKAhgQSjBogKSgFZBVRzHuVPjQVuDSwhfS
            dK6fkhy0S1lyiAyQYLo3p4hx00iyz45p5/C56qOMRLoNQI/mOvc40w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T03:54:31Z"
    mac: ENC[AES256_GCM,data:863aCTZX5H2HlmJ8MGWvF7lhhlsp/v3yX3T41wWeMdZ35lGaQaqyGqcvF2mH/iK1NQkMkzZFkIXwVLb0iB+C+V2Eiy+NQQc06f48lK3g4/5pvezB+Q5of0la+X5kmLSBufkP7S1R2RYwrS2kpK8YL5nKTfj50X0SAWQCAxeaI38=,iv:cueORpyS0PGSJrBNyxpDab1A99QeHyXk8UYB5FHCEQQ=,tag:kn30A/dPElLM7n4OROClKg==,type:str]
    version: 3.13.1
