apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zigbee2mqtt

resources:
  - namespace.yaml
  - storage.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
  - zigbee2mqtt-auth.sops.yaml

configMapGenerator:
  - name: zigbee2mqtt-seed
    files:
      - configuration.yaml
