apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  hostPath:
    path: /opt/zigbee2mqtt/data
    type: DirectoryOrCreate
  claimRef:
    namespace: zigbee2mqtt
    name: zigbee2mqtt-data-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data-pvc
  namespace: zigbee2mqtt
spec:
  storageClassName: local-nvme
  accessModes:
    - ReadWriteOnce
  volumeName: zigbee2mqtt-data-pv
  resources:
    requests:
      storage: 5Gi
