apiVersion: v1
data:
    HOME_ASSISTANT_TOKEN: ENC[AES256_GCM,data:kSTLA56tYPIV+/SCcqsOSLme2Hls6uiXW9US4ZtiD1Gh4ls5z0sKxO31HE5wB1Cu5yBdiOFOZkZdgiG3zmeRs1Bs+vRytWaOaFzf9D8OSTeOWmk6XPtgJt3ZDSrf6ZP4WTn0pNSm16o0lKgwRFFWpAA5rrNd4PeIb+WoSJdwzrCnnjI4PxfkV5hp72gPW96mwOTw91aNqBanFPBztjN4/7PtFaMrDOYr55LocpT4+gX9IgbuAdKKJmaHijB7ZE5rNwRdQTpvgug+pSNhdNSHvwEvxW1yNujRmqLlJ9V8cKX6ycEON3B2QzdTHJwUKarPxg3K2Q==,iv:IQ7Sko6T39DLolnGmp377n/u2rIaja/bvNsJ+Jxu/As=,tag:zYKP9vAsxoAw0QYSHdoWqg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:FLU0YLG92rHtyIJS2/VOXw==,iv:DSLG1Tu4s8kTKRkbZclYpnufZMwDOLIEnPkQiKFn/2s=,tag:ICpHHaBWhOmaokMmnZ98/w==,type:str]
    ROMM_DB_PASSWORD: ENC[AES256_GCM,data:ROk6sEeN7mtG6z5QTtCHM5FYBgrJ5HYaaOwwkXsS1nprosLY4vaCVkDU1sXtnOfBc9zbMyP4Ym+iszMM8TaLeA==,iv:0SiAv9frePwhEOQlagCOFHa4H8UM0XSJw/NRntNRy/I=,tag:UoT7yRbBAixg67wF8oL5bw==,type:str]
kind: Secret
metadata:
    name: restic-nas
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbi9oSXhjUkM2NjE2Ykcy
            aDhpQWI4VUNPV0V4Y1hWcUhNaVV3dEhkclQwCnYxUlIwMHkrM2JKQ29nbEJUSWZw
            eFlKWXB2ak1zNmR2UGxIS0JUVlFEZTQKLS0tIG9pZjBzamRDMzdUYk0rR3ZEekV0
            a1N1S2FmWmVpMi9kbDJ0QUcxeVFCVjgKlA+tGGmyeijeWudu2bOTBx1w50SU9mVT
            NCI9obzofu4LX8Qt95DF6RFlvLRSTRH+XlPd+N5cG2ViQJE6hgnI8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:17:35Z"
    mac: ENC[AES256_GCM,data:PYbyI2WbwyeWk6oXL3zaFUA3sVd+KejvFmE2qi2q+mblUV6QUrSeoVpHPCa3rTZCovl4KpDaYruRR6E0/HhZMkIUI8kHls/z5g5WJpakWnANE9ONpEIVCmwX+Vh/zp0sSQtUhK9ZPjc8daRpF8cn5FpiA/Q5Ykj+UOyv1w5ALYc=,iv:/kjwsdc9StGrshZq8KP4cSwqAgl6+aYlvBoJey81qMg=,tag:cpx7AFu4GHnPkHVYhcpWdg==,type:str]
    version: 3.13.1
