apiVersion: v1
data:
    HOME_ASSISTANT_TOKEN: ENC[AES256_GCM,data:vlwdUEkisswAxpGktYi+0kUDIT/diKTDiNbcVI8KCk9/3YaJADd52dMPIFyC88YuQxZrPxn00e5Ky0BMOEpikF4jnUJHWqPXKcAYfWrxbZiX2eGdkXU1dUArN0YEPnU+HAXSO7mvmuIRZwdDlZ7jR0qr8rVDlU7NIMo9VfT9M5qMQsm0piRCK/UoPvUtxHoJFTXToJIQeoP2Fp4mpXm5Uyg8P5K+pTHF/OZapwZ5vu6ZVyaRynKPCcJsLguHte/QXjuBsIIHDgZWfPmS46I0g8oh8UyYQyDhxdCjF5bAGUtOr4yl7LZ4TjlC3jfRMZGnvxkXlw==,iv:CFInT9OhUJWtTDGrYIaq/7FDhlutlT76gMf3jsmjlBo=,tag:Mg6i00YxmkVDxKH72ZlPOw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ltNp6Cztkp4gYs3XnzhGmg==,iv:8+1GYiOohufwTPQhCAVwCDP1UFCeqw0x7hyaIoFjF9U=,tag:6ZZRvw28aOFFqPRK9+9obw==,type:str]
    ROMM_DB_PASSWORD: ENC[AES256_GCM,data:kvXfbC+/3+9pbwb/qKLEMwo01k+kgKxvAkI4Qw2+ZcD02iQElyR/8LM5ElgWGZ3PVpxVEKLQS+X3j8Zt6HHzxiIWq0o=,iv:FBomE3nAvpeH/Wp5xx7XjlqhtH0ZgXbmGr2ONfznrzQ=,tag:EgvwLAFazvv/VxRMgrMatg==,type:str]
kind: Secret
metadata:
    name: restic-nas
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMkI0c0tDRGFQNzNwQ1BM
            TFR4Vmp2Y1pKVE16TTVweEd1REE5UHhPeEhFCjNMNTRjNnNYcTlMa0JiWkpjOUp3
            UkJJMGNDNHpPMVh6SGRlYjRTUXlQS0kKLS0tIEN1cmwwTjlwTjhzY2VQd2gyb1M2
            dmlraG4wODFCa0tkeHdwUEtaZXJXdlkKrKchtXsvJHQZLbt9juGcC5TdW/fWSa9Y
            zYAqv+r0CNgjroz4citU9bk0rTlmBEjOYMfGw4jMu8eU44yRQqfTQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T23:34:05Z"
    mac: ENC[AES256_GCM,data:Lk+HjIWHmwBnVLteDvvtrw1E02h41bGZNEhTMMiHUd+TEM3U2tgEhOHMXbjmqJi8vLbClVOvj044QWhi+mfEmKoE6pdgS5+9hxCAS2qpcZhsiZ/s9GOmcl+vtKYf75gBy+feD3mFsGcJHXpiimAyRI8GNc/4PLbt9uxL+pjZcO0=,iv:SoKCYryw2KTTJ/0k7lOVZjm3kKyZaeseCvphiujbkrE=,tag:bMiMksNeIkjtJP1ZAj77Jg==,type:str]
    version: 3.13.1
