apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:olbPaxv878pDnibLpLvadJZvmYm8sx/vfea2MMQ0CzIBIzP6,iv:nabqKmTrhQYWtiNdjgrxHIVqGYn7zv985x+eH1JlFh0=,tag:lVo90X2aLA+U+jlG764biA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:p6d4AUyyoc7VygBPb4lcq8oR0ZtDu5GIBPYLt+OSvzlJkC9zcERQ/+14QEg=,iv:RVcSeKYWP1QTh9EgrjyPYvWRWHzXcFSntDHp9Vgt5SM=,tag:2kLYerfl4AK+ca+F+aqZkQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:n4OgmttJ4ufHcNf5hgPjlZOpn5e8iU9+ajJuPy/8puqtwEBJ,iv:iReS77cwgTyCgK7vlUHDPEp0faHgGLnRYlzNVVSVhlg=,tag:3KsRwPO5n3TqITPha/8jdQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:LsVX6JA6yrztjj+mI/McA2+UUJsC/gq4/hSUaTLTacH3vRJY+oSS7jJhFSTW3pPeWd8roCmE658RdFBb/OFMRFSP5tD3R5LJlwGwbmwXu4/qiVMCjHSYmw==,iv:iRqVMXzotk8T+5dZl4YgYRVQYSEBQkl3ueHJQIFiQDc=,tag:qK+qvFr3wRQ4Gx+V7LYkYw==,type:str]
kind: Secret
metadata:
    name: restic-b2
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdUhwNWhhZXp3cFNnU1hI
            UFBVSUVrZi8wb3g2WTRlUldaS1crdWpOWnpBCncwcEFsdy9tYkVWN1AzZFNKajR5
            MHZUTURDWXduMHoyZEU2M3kxdU5oU2MKLS0tIGpiUHBjZThHQWJJWGRtanp5dDBR
            MWJRdW5wQVlCUlJPYlhtd2R1YlVxVHcKmZsvrJ4hTor/nEGwQmiVaEFXmQopsUqK
            QCwdNlMV81Tx4xtL+xcEh0I7YHN3Wwz5i0dZBfm801anRitqJxKfYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T15:09:50Z"
    mac: ENC[AES256_GCM,data:PC4v/CdPGqq1UlO3ZfpLY/7tBuLCSxwVLEc/o7/uFft2rrRDQ4T12JFLXBhLG3DJ/SA0OdfqFIyr5fXP/oZ38bZ+bupthGonSo89nL4uQoM1EKrGEk4C/5eG44PzpqYCNeGLHZs3cn9dAhgY5he0nhGkWU0OHmrVu25qk5byD3c=,iv:zHXH8F/v/JGadtfuByNZ5cM8KCx5DE7uszy8B65XnrI=,tag:jwzrPyT7Ko7Pz3VkGHn9Og==,type:str]
    version: 3.13.1
