apiVersion: v1
data:
    HOME_ASSISTANT_TOKEN: ENC[AES256_GCM,data:vbU9vT2DSHKdfcYq+YQM7romlYDUbzRmeMRD6p7qoDzuco0B6eh/rwkJfPh5hxFXcdn/nu28IHFnLpmcQjKTbIntnGAZ6bba+TdHkREA7dG4NxGa3cUJxUYnKk1wtbG2aVALvgIUgfvGE+9acc2UBp91R2HkegcEFuYsIbLFmf2x1CdF80eLZOGWDcUCG80fvacTtHUlcAufz2SU7y7imQjVa942RSRd8urjMOFM59aELdVBJmQl527+XpCcZo93stiwtRkOsxamIcmW8EcfTBkPAUipmX/3G3zfC67zHRafKSTB8dNm2biJxJZMR95e9TUeBQ==,iv:FQxVbdAFyX8nQKZch/NztEXjh/7N14x5E0fccGa0P3E=,tag:VAeDJsntwa+7EfXh7EI67A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ZW5iWH4/ntGzFdinv5SgBg==,iv:WOGXECMWo++av6ZzZUanPJFJn3/fqQ2dhDcCj2Nrguw=,tag:KK5cJDFU87NXl/uyJyyRfA==,type:str]
    ROMM_DB_PASSWORD: ENC[AES256_GCM,data:BtRLVifdmJ20eplmnYHH7vaye49ZmwCRQnlznzwzYVj5VtNs2pie12K+Q0/0Ts7bFTybsl3LarQnDP23gm8/U3FAA2w=,iv:0I4BMghTtoInQXRBvbdmj7CnhboKxloetwVquBXJLzw=,tag:WTX2UmmuvQvm1yob/n8DxQ==,type:str]
kind: Secret
metadata:
    name: restic-nas
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUHltWlcrMVJySDdXcGJp
            VU1pNkF3Z3RHMDZOajV1ZGZibVgvbnBxQ1dRCjJQVks0Y2tUdW8rU3lpWEYwT3ZU
            ZGo1YVBXWVdaTTNiTThhRUovNCtydVkKLS0tIGpVQWZqcFdsRXdUUi9uOTNQK1RQ
            ZGxYZ3RIMHFRK3FZQ3VrY1ovU2FHK1EKdEkEnlSuORNnw0hwRfkXXxuLdEuYKyB8
            3wwwfqXUpgNS2nh2HkWF4UPPtgqorog+CIyS9Y0eSW3ol0scGzX2LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T23:17:30Z"
    mac: ENC[AES256_GCM,data:8qQpyq5O9vQ3uiY9vQ66MgmIYG3Bp1AbZiLhb1F9DDLFT11JYHboDaAjKLnlnpqOggB9/N/Co0mHJyclSASxRcGZsBoC4OycDL2LPJu/ira3D8HDoHNgz7Ss7/9cCrZf/rOmy1RjM47ROTEQzJB9EIbbovLKfgijgaOY9iJYug0=,iv:VdFQXWjTVHyRKlFFGLrVsFSoLwfiE2itd1pqNGM/NBs=,tag:MAF/uwFHIVUEWi2qemh+/g==,type:str]
    version: 3.13.1
