version: 0.17-0

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detectors:
  coral:
    type: edgetpu
    device: usb

objects:
  track:
    - person
    - dog

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - person
      - dog

snapshots:
  enabled: true
  retain:
    default: 14

record:
  enabled: true
  continuous:
    days: 1
  motion:
    days: 0
  alerts:
    retain:
      days: 365
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

cameras:
  amcrest_105_50:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAMERA_AMCREST_105_50_RTSP_USER}:{FRIGATE_CAMERA_AMCREST_105_50_RTSP_PASSWORD}@192.168.105.50:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_CAMERA_AMCREST_105_50_RTSP_USER}:{FRIGATE_CAMERA_AMCREST_105_50_RTSP_PASSWORD}@192.168.105.50:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
    detect:
      enabled: true
      fps: 5
    motion:
      mask:
        - 0.664,0.033,0.664,0.075,0.969,0.079,0.969,0.031
    notifications:
      enabled: true
      email: frigate@wormpoint.com
      cooldown: 300
