apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  hostPath:
    path: /opt/frigate/config
    type: DirectoryOrCreate
  claimRef:
    namespace: frigate
    name: frigate-config-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate
spec:
  storageClassName: local-nvme
  accessModes:
    - ReadWriteOnce
  volumeName: frigate-config-pv
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-cache-pvc
  namespace: frigate
spec:
  storageClassName: topolvm-scratch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
