apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

resources:
  - namespace.yaml
  - storage.yaml
  - zwave-js-storage.yaml
  - service.yaml
  - zwave-js-service.yaml
  - ingress.yaml
  - deployment.yaml
  - zwave-js-deployment.yaml

configMapGenerator:
  - name: home-assistant-seed
    files:
      - configuration.yaml
      - automations.yaml
