# mdadm.conf
#
# Run update-initramfs -u after installing this file.

# Treat arrays created on another host as foreign unless explicitly listed below.
HOMEHOST <system>

# Local delivery target for mdadm monitoring alerts.
MAILADDR root

# Do not autoassemble unlisted arrays.
AUTO -all

# Bulk-storage RAID6 migrated intact from Morpheus.
ARRAY /dev/md3 metadata=1.2 UUID=74071d44:3bf857f0:85a3a734:9391a964
