apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-controllers
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  path: ./infrastructure/monitoring/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
