apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: media
  labels:
    app.kubernetes.io/name: download-stack
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: download-stack
  template:
    metadata:
      labels:
        app.kubernetes.io/name: download-stack
    spec:
      priorityClassName: homelab-standard
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027
          envFrom:
            - secretRef:
                name: gluetun-mullvad
          env:
            - name: VPN_SERVICE_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: VPN_SERVICE_PROVIDER
            - name: VPN_TYPE
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: VPN_TYPE
            - name: SERVER_COUNTRIES
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: SERVER_COUNTRIES
            - name: FIREWALL_INPUT_PORTS
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: FIREWALL_INPUT_PORTS
            - name: FIREWALL_OUTBOUND_SUBNETS
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: FIREWALL_OUTBOUND_SUBNETS
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: gluetun-config
                  key: TZ
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
        - name: sabnzbd
          image: lscr.io/linuxserver/sabnzbd:5.1.2-ls271@sha256:64c4c2b6ed546237451cbfec33aa8bac1396865c1a266dd247c02b36ffe27c62
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: sabnzbd
              containerPort: 8080
          resources:
            requests:
              cpu: 125m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: sabnzbd-config
              mountPath: /config
            - name: sabnzbd-incomplete
              mountPath: /incomplete
            - name: media
              mountPath: /media
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:5.2.3_v2.0.14-ls474@sha256:a00b6a597a3832a1814cde0ef60abc55c94644f3f80902c3432f6af6de8d4a96
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
            - name: WEBUI_PORT
              value: "8090"
            - name: TORRENTING_PORT
              value: "6881"
          ports:
            - name: qbittorrent
              containerPort: 8090
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-incomplete
              mountPath: /incomplete
            - name: media
              mountPath: /media
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:2.5.2.5491-ls158@sha256:91844fa2c927ad6ede5630127183cc7868b175f6223e83e6a5da1fffea2aa782
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: prowlarr
              containerPort: 9696
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          volumeMounts:
            - name: prowlarr-config
              mountPath: /config
        - name: radarr
          image: lscr.io/linuxserver/radarr:6.3.0.10514-ls314@sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: radarr
              containerPort: 7878
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: "1"
              memory: 768Mi
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: media
              mountPath: /media
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.19.2979-ls322@sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Chicago
          ports:
            - name: sonarr
              containerPort: 8989
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 768Mi
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: sabnzbd-config
          persistentVolumeClaim:
            claimName: sabnzbd-config-pvc
        - name: sabnzbd-incomplete
          persistentVolumeClaim:
            claimName: sabnzbd-incomplete-pvc
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qbittorrent-incomplete
          persistentVolumeClaim:
            claimName: qbittorrent-incomplete-pvc
        - name: prowlarr-config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-config-pvc
        - name: media
          hostPath:
            path: /mnt/media
            type: Directory
