apiVersion: v1
data:
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:4QwA05euDYU19TOc0IX7o73QVeQzvggmc6uCUsyp3nnDtAjy1lSRHBmfG1XxkdadMvF3+MKE7OEu3FhWvlB6RA==,iv:y8BPqvkwDtk8KKnVjATCPlZmD2kac70dUfuCeck8pCk=,tag:Z+/vK6543E4xkSxg4jZozw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PdsOgYWAlHwOYfMpdtJG+zVEDirDQUPRLNBqO/Wq97+uBcTQ4rb3n7kXkbragZyb7wb7BnjVSuiDNpG3,iv:dD2QmeDD3qbD89D8dTVOWO6UPAwKVVhRGvJNdobDV64=,tag:SaJKcvZW9u/wXoReIsJ6pQ==,type:str]
kind: Secret
metadata:
    name: gluetun-mullvad
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSWZPQzg1OHZ0YkJ2NWJw
            cGd2NlRWS09BQUdDSmVIWG1WbUFJWUhzaEU0CmZuTmNVNnVRb3U2VkFydWFHZ1Fk
            UkFHY3NGaThqY3dnb0U2UnB0ZlVKbHMKLS0tIFA5ckMvMXZqWkNNQVZXNmtpbFQx
            eWl4b0lDTmIrU29VcDNDU3NZWnkxRncKqNbr+hpgyJEb1SUzLrA5XJ7OJ6YhiRty
            J9nha86JnAPmJDQ+Ev023mtCvCn+K9CaNNheiQqqivyhxsMnd6N8Xw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T04:47:36Z"
    mac: ENC[AES256_GCM,data:AG117vI4pHYjSwBQgm+4b3GlD3Odr90nxcxdbF6wEXe3YkK4bcTgtZT+s36BiUOK/JDs/znvvEJXrOAseBsbjA3MWsb9tNk7H1+boxjSIaTWkiOL/MhaU4ayxq8G8Jzz7qxJFPf4sy6nvMEbwQq+OeuHexYQCuNeofxx/USfTYc=,iv:Qr7qXZ0eDE/JfjCU9ZZ9ABfu3AsNAggrhGr5hXhx1/Y=,tag:zvL8rb969+UrqfndWDAlYg==,type:str]
    version: 3.13.1
