apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-incomplete-pvc
  namespace: media
spec:
  storageClassName: topolvm-scratch
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
