[Service]
ExecStartPre=/bin/sh -c 'if [ -w /sys/block/md3/md/sync_speed_max ]; then echo 50000 > /sys/block/md3/md/sync_speed_max; fi'
ExecStopPost=/bin/sh -c 'if [ -w /sys/block/md3/md/sync_speed_max ]; then echo system > /sys/block/md3/md/sync_speed_max; fi'
