apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  hostPath:
    path: /opt/mosquitto/data
    type: DirectoryOrCreate
  claimRef:
    namespace: mqtt
    name: mosquitto-data-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-pvc
  namespace: mqtt
spec:
  storageClassName: local-nvme
  accessModes:
    - ReadWriteOnce
  volumeName: mosquitto-data-pv
  resources:
    requests:
      storage: 2Gi
