apiVersion: v1
data:
    MOSQUITTO_ZIGBEE2MQTT_PASSWORD: ENC[AES256_GCM,data:I3VWyhvH9Of4vtN/NYvfqc36ThLMQmuau6JMtmkSQ2awPc8BoUSX8L1/x+jQB2idNjXTOPihihAUXuD4qutgWGZU1hfe89GGf18/zwj54G/c7V1iF24jLQ==,iv:SDajBUK/SFOGr3/YI8NAXJ6WT9HMMVdLhCSLzmC9kY4=,tag:TF4dxwtkkdpw8o55kBlVlw==,type:str]
    MOSQUITTO_ZIGBEE2MQTT_USER: ENC[AES256_GCM,data:K+QEIs31FarKPlEqF73mdA==,iv:13l+83lxYEiSemGDWsJ7fCBSccpVoTtONlm8hhlDAHQ=,tag:1GpajaelxWfG9V/2UX5DZg==,type:str]
kind: Secret
metadata:
    name: zigbee2mqtt-auth
    namespace: mqtt
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrenVXWjFOdnI1VEdYVGM1
            WkRWYlFra1ozSGNHVHAxMWxsNFlBOWxKSlNvCnEyNG90cnVsS1ZlUkRIU2l1OTB0
            MGdaZDh5emxublQ3K3BORkRHU1FQTlEKLS0tIHh1czdDa3RON0hqRm5KYVBoTmx3
            anR1WW9zKzFLSkw2S3RQY25sZlRsWmcKsEEnnRErE6NDihYGag51hMPsBmshAVDW
            lcN5GTd8C7LmmVkTHmirVBkO9INpNVkdtSMrWnxa7uv16SnV+9/LRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18cxm2hs3ctq0s735h7z9lj7w7ag37f2vleesglcw6lezlhy5v9nsatkxex
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T16:08:20Z"
    mac: ENC[AES256_GCM,data:FWvJali6bAlFl0YjNmtvC5GpnYqjtZMH0TmqirzOVAI9ZCcu26dtUlnqy/k2BBxL7sL2rSqR20CPbt6tVuddftlKQu3Z1fx8aKwWXOWYAccYR09ncDb7XRwb/urW5t+YJQjMmWt4W/cFXNNUvVTEA+RHrgBH9h1vW42qU24o1FQ=,iv:VTsnQ3Y9n6vgB8t96BFSyEMEhQxdcvs8kObwev/hDmw=,tag:ZRUwIJQo07hO8liAb2ZWvw==,type:str]
    version: 3.13.3
